
services:
  # dev mode makes it easier for us to update whiel coding
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app      # Bind mount to reflect live changes
      - /app/node_modules    # Prevent overwriting node_modules
    ports:
      - "5173:5173"          # Or whatever port your dev server uses
    develop:
      watch:
        - path: ./frontend
          target: /app
          action: sync
    depends_on:
      - backend
  # for when we want to build it
    # frontend:
    #   build:
    #     context: ./frontend
    #     dockerfile: Dockerfile
    #   develop:
    #     watch:
    #       - path: ./frontend
    #         target: /app
    #         action: sync
    #   ports:
    #     - "80:80"          # nginx serves your frontend on port 80
    #   depends_on:
    #     - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"      # Rails app on port 3000 (or 80 depending on your setup)
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/myapp_production
      - RAILS_MASTER_KEY
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

