
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"          # nginx serves your frontend on port 80
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"      # Rails app on port 3000 (or 80 depending on your setup)
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/myapp_production
      - RAILS_MASTER_KEY
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

